import { ArrowDown, Download, Github, Linkedin, MapPin } from "lucide-react";

const Hero = () => {
  const scrollTo = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: "smooth" });
  return <header className="resume-paper relative px-6 pb-10 pt-6 md:px-12 md:pb-14 md:pt-8">
    <nav className="mb-10 flex items-center justify-between border-b border-border pb-4 text-xs font-bold uppercase tracking-[0.16em] text-muted-foreground">
      <button onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })} className="resume-label">IP / portfolio</button>
      <div className="flex gap-4 md:gap-7"><button onClick={() => scrollTo("experience")} className="hover:text-primary">Experience</button><button onClick={() => scrollTo("projects")} className="hover:text-primary">Projects</button><button onClick={() => scrollTo("contact")} className="hover:text-primary">Contact</button></div>
    </nav>
    <div className="grid gap-10 md:grid-cols-[0.8fr_1.2fr] md:gap-16">
      <div className="flex flex-col justify-between"><div><p className="resume-label mb-4 text-lg">Hello, I’m</p><h1 className="text-5xl font-black leading-[0.88] tracking-[-0.08em] text-foreground md:text-8xl">Indra<br />Purnomo<span className="text-primary">.</span></h1><p className="mt-5 max-w-xs text-xl font-bold leading-tight text-primary">Software Developer<br />building useful things with code.</p></div><div className="mt-10 flex flex-wrap gap-4 text-xs font-semibold text-muted-foreground"><span><MapPin className="mr-1 inline h-3.5 w-3.5 text-primary" />Indonesia</span><a href="https://github.com/ndraoo" target="_blank" rel="noreferrer" className="hover:text-primary"><Github className="mr-1 inline h-3.5 w-3.5" />GitHub</a><a href="https://www.linkedin.com/in/indra-purnomo-a36014291/" target="_blank" rel="noreferrer" className="hover:text-primary"><Linkedin className="mr-1 inline h-3.5 w-3.5" />LinkedIn</a></div></div>
      <div className="border-l-0 border-border md:border-l md:pl-12"><p className="resume-heading mb-3 text-xl">About me</p><p className="resume-copy max-w-2xl text-sm md:text-base">I am Indra Purnomo, a Software Developer working across backend, frontend, and mobile development. I specialize in PHP Laravel, JavaScript, Golang, Vue.js, React.js, and React Native, with a focus on building efficient, secure, and scalable applications.</p><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-4"><div className="rounded-xl bg-secondary p-3"><strong className="block text-xl text-primary">01+</strong><span className="text-[10px] font-semibold text-muted-foreground">year experience</span></div><div className="rounded-xl bg-secondary p-3"><strong className="block text-xl text-primary">05</strong><span className="text-[10px] font-semibold text-muted-foreground">projects</span></div><div className="rounded-xl bg-secondary p-3"><strong className="block text-xl text-primary">04</strong><span className="text-[10px] font-semibold text-muted-foreground">workplaces</span></div><a href="/indra-purnomo.pdf" download className="rounded-xl bg-primary p-3 text-primary-foreground transition-opacity hover:opacity-80"><Download className="mb-1 h-4 w-4" /><span className="block text-[10px] font-semibold">my resume ↗</span></a></div><button onClick={() => scrollTo("experience")} className="mt-9 text-xs font-bold uppercase tracking-[0.16em] text-primary hover:text-accent">Scroll to explore <ArrowDown className="ml-1 inline h-3.5 w-3.5" /></button></div>
    </div>
  </header>;
};
export default Hero;
