import { useState } from "react";
import { ArrowUpRight, ChevronDown, ChevronUp } from "lucide-react";

const experiences = [
  { title: "Software Developer", company: "Pinetop Technology plt.", period: "Dec 2025 — Present", points: ["Working on TalentCloud.Ai with a focus on fullstack development.", "Developing and maintaining fullstack features using PHP Laravel for backend, Vue.js and React.js for frontend, and React Native for mobile development.", "Implementing form management features with complete flow from frontend UI and API integration to backend business logic and database operations.", "Collaborating with cross-country engineering teams in Malaysia and Indonesia to deliver integrated fullstack solutions."] },
  { title: "Backend Developer", company: "Putra Muda Mandiri", period: "Apr 2025 — Present", points: ["Developed a POS (Point of Sale) system for restaurants with dynamic menu and order management features.", "Developed backend APIs using Firebase Cloud Messaging to schedule and send push notifications based on user roles and topics.", "Developed and maintained new features, including notifications, invoices, and attendance (presences) endpoints.", "Contributed to backend system architecture, endpoint testing, and collaborated closely with cross-functional teams.", "Followed clean code principles and utilized Git for version control and collaborative development."] },
  { title: "Backend Developer Intern", company: "Core Initiative", period: "Oct 2024", points: ["Developed secure backend features for user profile updates and password changes, implementing validation and encryption for data protection.", "Implemented soft delete functionality using Eloquent ORM, enabling reversible data removal and improving data safety.", "Built a recurring booking management system that allows users to schedule repeated reservations with optimized database queries.", "Designed and managed backend logic for room amenities, enabling dynamic configuration and integration with the booking system."] },
  { title: "Web Development Intern", company: "PT Dewan Studio", period: "Feb 2023 — Mar 2023", points: ["Developed an Inventory Management website using Laravel 9.", "Developed a Financial Monitoring website for a mosque using Laravel 9."] },
];

const WorkExperience = () => {
  const [expanded, setExpanded] = useState(false);
  return <section id="experience" className="relative px-6 py-28 md:px-10"><div className="mx-auto max-w-6xl"><div className="mb-14 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow mb-4 text-xs text-primary">01 / Experience</p><h2 className="display-heading text-5xl font-bold md:text-6xl">Where I’ve been<br /><span className="text-muted-foreground">putting code to work.</span></h2></div><p className="max-w-xs text-sm leading-relaxed text-muted-foreground">A detailed timeline of the teams, products, and problems that shaped my approach.</p></div><div className="divide-y divide-border border-y border-border">{experiences.slice(0, expanded ? 3 : 2).map((exp, index) => <article key={exp.company} className="group grid gap-5 py-8 transition-colors hover:bg-card/40 md:grid-cols-[120px_1fr_1.6fr] md:gap-10"><p className="font-mono text-xs text-muted-foreground">0{index + 1} / {exp.period}</p><div><h3 className="text-xl font-semibold group-hover:text-primary">{exp.title}</h3><p className="mt-1 text-sm text-primary">{exp.company}</p></div><div className="flex items-start justify-between gap-6"><ul className="max-w-xl list-disc space-y-2 pl-4 text-sm leading-6 text-muted-foreground">{exp.points.map((point) => <li key={point}>{point}</li>)}</ul><ArrowUpRight className="hidden h-5 w-5 shrink-0 text-border transition-transform group-hover:-translate-y-1 group-hover:translate-x-1 group-hover:text-primary md:block" /></div></article>)}</div><button onClick={() => setExpanded(!expanded)} className="mt-8 text-sm font-semibold text-primary transition-colors hover:text-accent">{expanded ? <>Show less <ChevronUp className="ml-1 inline h-4 w-4" /></> : <>View full experience <ChevronDown className="ml-1 inline h-4 w-4" /></>}</button></div></section>;
};
export default WorkExperience;
